#!/usr/bin/env python3
"""Erzeugt alle Platzhalter-Texturen des Add-Ons aus ASCII-Pixelart.

Alle Assets werden hier prozedural erzeugt - keine fremden Bilddaten, keine
Vanilla-Assets. Ausfuehren mit:  python3 tools/gen_textures.py
"""
import os
import struct
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ITEMS = os.path.join(ROOT, "resource_packs", "px_weapons_rp", "textures", "items")
ENTITY = os.path.join(ROOT, "resource_packs", "px_weapons_rp", "textures", "entity")
UI = os.path.join(ROOT, "resource_packs", "px_weapons_rp", "textures", "ui")

PALETTE = {
    ".": (0, 0, 0, 0),
    "k": (26, 26, 28, 255),      # Outline
    "d": (58, 63, 68, 255),      # Dunkles Metall
    "g": (107, 112, 118, 255),   # Metall
    "l": (154, 160, 166, 255),   # Helles Metall
    "w": (216, 220, 224, 255),   # Klinge
    "b": (107, 74, 43, 255),     # Holz
    "B": (74, 51, 32, 255),      # Dunkles Holz
    "o": (224, 138, 46, 255),    # Messing
    "r": (192, 57, 43, 255),     # Rot
    "y": (232, 197, 71, 255),    # Gelb / Flamme
    "s": (91, 122, 153, 255),    # Glas / Optik
    "c": (63, 184, 200, 255),    # Akzent
    "n": (74, 122, 58, 255),     # Oliv
}


def write_png(path, width, height, rows):
    raw = b""
    for row in rows:
        raw += b"\x00" + b"".join(bytes(px) for px in row)

    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    blob = b"\x89PNG\r\n\x1a\n"
    blob += chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
    blob += chunk(b"IDAT", zlib.compress(raw, 9))
    blob += chunk(b"IEND", b"")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(blob)


def from_art(path, art):
    lines = [line for line in art.strip("\n").split("\n")]
    size = max(len(lines), max(len(line) for line in lines))
    rows = []
    for y in range(size):
        line = lines[y] if y < len(lines) else ""
        line = line.ljust(size, ".")
        rows.append([PALETTE[ch] for ch in line[:size]])
    write_png(path, size, size, rows)


ART = {}

ART["px_pistol"] = """
................
................
...kkkkkkkk.....
...kddddddk.....
...kdllllgk.....
...kdkkkkkk.....
...kdk..........
...kBk..........
...kBBk.........
...kBBk.........
....kBBk........
....kBBk........
.....kkk........
................
................
................
"""

ART["px_smg"] = """
................
................
..kkkkkkkkkkkk..
..kdddddddddgk..
..kdllllllllkk..
..kdkkkkkkkk....
..kdk...........
..kdk...........
..kBk...........
..kBBk..........
..kBBk..........
...kBk..........
...kkk..........
................
................
................
"""

ART["px_rifle"] = """
................
................
......kkk.......
kkkkkkkdkkkkkkk.
kdddddddddddddk.
kdllllllllllllk.
kkkkkdkkkkkkkkk.
.kBkkdk.........
.kBkkdk.........
.kkk.kdk........
.....kdk........
.....kdk........
.....kkk........
................
................
................
"""

ART["px_shotgun"] = """
................
................
................
..kkkkkkkkkkkkk.
..kdddddddddlgk.
..kkkkkkkkkkkkk.
..kdddddddddlgk.
..kkkkkkkkkkkkk.
.kBBk...........
kBBk............
kBk.............
kk..............
................
................
................
................
"""

ART["px_sniper"] = """
................
......kkkk......
......ksskk.....
kkkkkkkllllkkkk.
kdddddddddddddk.
kdllllllllllllk.
kkkkkkdkkkkkkkk.
..kBBkdk........
...kBkkk........
...kkk..........
................
................
................
................
................
................
"""

ART["px_minigun"] = """
................
................
................
.kkkkkkkkkkk....
.kdddddddddk....
kkkkkkkkkkkkkk..
kllllllllllllk..
kkkkkkkkkkkkkk..
.kdddddddddk....
.kkkkkkkkkkk....
...kdcccdk......
...kddddddk.....
....kkkkkk......
................
................
................
"""

ART["px_bazooka"] = """
................
................
................
....kkkkkkkkkkk.
...kdddddddddddk
..krggggggggggdk
...kdddddddddddk
....kkkkkkkkkkk.
.....kdk........
.....kBk........
.....kkk........
................
................
................
................
................
"""

ART["px_turret"] = """
................
................
................
.....kkk........
.....kdk........
...kkkdkkk......
...kdgggdk......
...kdgcgdk......
...kdgggdk......
...kkkkkkk......
..kddddddddk....
..kdllllllldk...
..kkkkkkkkkkk...
................
................
................
"""

ART["px_balisong"] = """
..............k.
.............kw.
............kwwk
...........kwwk.
..........kwwk..
.........kwwk...
........kwwk....
.......kwwk.....
......kdgk......
.....kddk.......
....kddk........
...kddk.........
..kddk..........
..kkk...........
................
................
"""

ART["px_karambit"] = """
................
.........kkk....
........kwwwk...
.......kwwk.....
......kwwk......
.....kwwk.......
....kwwk........
....kwk.........
...kwwk.........
...kdgk.........
..kddk..........
..kdk...........
.kdkkk..........
.kdk.k..........
..kkkk..........
................
"""

ART["px_grenade_frag"] = """
................
................
................
......kk........
......kdk.......
....kkkkkk......
...knnnnnnk.....
...knknknnk.....
...knnknknk.....
...knknknnk.....
...knnnnnnk.....
....kkkkkk......
................
................
................
................
"""

ART["px_grenade_smoke"] = """
................
................
................
....kkkk........
....kddk........
...kkkkkk.......
...kglllgk......
...kglllgk......
...kglllgk......
...kgcccgk......
...kglllgk......
...kkkkkkk......
................
................
................
................
"""

ART["px_grenade_molotov"] = """
................
................
.....kk.........
....kyk.........
....kok.........
....kkk.........
...kkgkk........
...kgggk........
..kkgggkk.......
..krrrrrk.......
..krrrrrk.......
..krrrrrk.......
..kkkkkkk.......
................
................
................
"""

ART["px_ammo"] = """
................
................
....kk...kk.....
...kyyk.kyyk....
...kyyk.kyyk....
...kook.kook....
...kook.kook....
...kook.kook....
...kook.kook....
...kggk.kggk....
...kggk.kggk....
....kk...kk.....
................
................
................
................
"""

ART["px_rocket"] = """
................
................
.....kk.........
....krrk........
....krrk........
....kddk........
....kddk........
....kddk........
....kddk........
...kkddkk.......
...kdkkdk.......
...kk..kk.......
................
................
................
................
"""



def crosshair(size=21):
    """Fadenkreuz: vier Striche und ein Punkt, weiss mit dunkler Kontur.

    Die Kontur sorgt dafuer, dass es auf hellem wie dunklem Hintergrund
    sichtbar bleibt.
    """
    mid = size // 2
    white = set()
    for offset in range(2, 7):
        white.add((mid, mid - offset))
        white.add((mid, mid + offset))
        white.add((mid - offset, mid))
        white.add((mid + offset, mid))
    white.add((mid, mid))

    outline = set()
    for x, y in white:
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                spot = (x + dx, y + dy)
                if spot not in white and 0 <= spot[0] < size and 0 <= spot[1] < size:
                    outline.add(spot)

    clear = (0, 0, 0, 0)
    bright = (255, 255, 255, 235)
    dark = (0, 0, 0, 170)
    rows = []
    for y in range(size):
        row = []
        for x in range(size):
            if (x, y) in white:
                row.append(bright)
            elif (x, y) in outline:
                row.append(dark)
            else:
                row.append(clear)
        rows.append(row)
    return size, rows


def flat(size, base, accent, border):
    rows = []
    for y in range(size):
        row = []
        for x in range(size):
            edge = x < 2 or y < 2 or x >= size - 2 or y >= size - 2
            if edge:
                row.append(border)
            elif (x // 4 + y // 4) % 2 == 0:
                row.append(base)
            else:
                row.append(accent)
        rows.append(row)
    return rows


def main():
    for name, art in ART.items():
        from_art(os.path.join(ITEMS, name + ".png"), art)

    # Fadenkreuz fuer die HUD-Ueberlagerung
    size, rows = crosshair()
    write_png(os.path.join(UI, "px_crosshair.png"), size, size, rows)

    # Turret-Entity-Textur: schlichtes Metallmuster, alle UVs zeigen darauf.
    write_png(os.path.join(ENTITY, "px_turret.png"), 64, 64,
              flat(64, PALETTE["d"], PALETTE["g"], PALETTE["k"]))

    # Pack-Icons
    for pack in ("behavior_packs/px_weapons_bp", "resource_packs/px_weapons_rp"):
        write_png(os.path.join(ROOT, pack, "pack_icon.png"), 64, 64,
                  flat(64, PALETTE["d"], PALETTE["c"], PALETTE["k"]))

    print("Texturen erzeugt:", len(ART) + 4)


if __name__ == "__main__":
    main()
